// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

maps/bts_rc.gmr
maps/bts_rc.gsr
maps/bts_rc.res
maps/bts_rc_motd.txt
models/bts_rc/furniture/a1_debris.mdl
models/bts_rc/furniture/a4_pipework1.mdl
models/bts_rc/furniture/a4_pipework2.mdl
models/bts_rc/furniture/admin_console.mdl
models/bts_rc/furniture/army_truck2.mdl
models/bts_rc/furniture/army_truck2_blk.mdl
models/bts_rc/furniture/barrel.mdl
models/bts_rc/furniture/barrel2.mdl
models/bts_rc/furniture/barrel3.mdl
models/bts_rc/furniture/bed.mdl
models/bts_rc/furniture/bigdoor.mdl
models/bts_rc/furniture/book_black.mdl
models/bts_rc/furniture/book_blue.mdl
models/bts_rc/furniture/book_red.mdl
models/bts_rc/furniture/bookshelf.mdl
models/bts_rc/furniture/bts_sign1.mdl
models/bts_rc/furniture/bts_sign2.mdl
models/bts_rc/furniture/cafeteria_chair.mdl
models/bts_rc/furniture/cafeteria_table.mdl
models/bts_rc/furniture/coffee_machine.mdl
models/bts_rc/furniture/couch.mdl
models/bts_rc/furniture/couch_station.mdl
models/bts_rc/furniture/couch_station_small.mdl
models/bts_rc/furniture/d0_holo_display.mdl
models/bts_rc/furniture/d0_tram.mdl
models/bts_rc/furniture/d0_tramarch.mdl
models/bts_rc/furniture/d1_bg_corridor.mdl
models/bts_rc/furniture/d2_generator.mdl
models/bts_rc/furniture/d3_bridgecontrol_a.mdl
models/bts_rc/furniture/d3_bridgecontrol_b.mdl
models/bts_rc/furniture/d3_bridgecontrol_C.mdl
models/bts_rc/furniture/d3_bridgepipes.mdl
models/bts_rc/furniture/d3_bridgevents.mdl
models/bts_rc/furniture/d3_burstpipe.mdl
models/bts_rc/furniture/d3_security_console.mdl
models/bts_rc/furniture/d3_sewagecontrol.mdl
models/bts_rc/furniture/d3_truss.mdl
models/bts_rc/furniture/d3_truss_corridor.mdl
models/bts_rc/furniture/d3_vents.mdl
models/bts_rc/furniture/d4_door.mdl
models/bts_rc/furniture/d4_fishtank.mdl
models/bts_rc/furniture/d4_scanners.mdl
models/bts_rc/furniture/d4_security_console.mdl
models/bts_rc/furniture/d4_securitycomputer.mdl
models/bts_rc/furniture/d4_securitydetails.mdl
models/bts_rc/furniture/d4_sentrycontrol.mdl
models/bts_rc/furniture/d4_tram_monitors.mdl
models/bts_rc/furniture/d4_weaponlocker1.mdl
models/bts_rc/furniture/d4_weaponlocker2.mdl
models/bts_rc/furniture/d4_weaponlocker3.mdl
models/bts_rc/furniture/d4_weaponlocker4.mdl
models/bts_rc/furniture/d4_weaponlocker5.mdl
models/bts_rc/furniture/d4_windowframe_1.mdl
models/bts_rc/furniture/d4_windowframe_2.mdl
models/bts_rc/furniture/d6_pipes.mdl
models/bts_rc/furniture/dorms_table.mdl
models/bts_rc/furniture/eye_scanner_broken.mdl
models/bts_rc/furniture/floodlight.mdl
models/bts_rc/furniture/forklift_static.mdl
models/bts_rc/furniture/gear.mdl
models/bts_rc/furniture/kitchen_pot.mdl
models/bts_rc/furniture/ladders.mdl
models/bts_rc/furniture/lambda.mdl
models/bts_rc/furniture/microwave.mdl
models/bts_rc/furniture/misc_billboard1.mdl
models/bts_rc/furniture/misc_billboard2.mdl
models/bts_rc/furniture/misc_billboard3.mdl
models/bts_rc/furniture/misc_billboard4.mdl
models/bts_rc/furniture/misc_billboard5.mdl
models/bts_rc/furniture/misc_caution.mdl
models/bts_rc/furniture/misc_chair.mdl
models/bts_rc/furniture/misc_chair2.mdl
models/bts_rc/furniture/misc_elevator_detail.mdl
models/bts_rc/furniture/misc_fireext.mdl
models/bts_rc/furniture/misc_folders1.mdl
models/bts_rc/furniture/misc_folders2.mdl
models/bts_rc/furniture/misc_folders3.mdl
models/bts_rc/furniture/misc_fusebox.mdl
models/bts_rc/furniture/misc_gauge_equip.mdl
models/bts_rc/furniture/misc_handdryer.mdl
models/bts_rc/furniture/misc_healthstation1.mdl
models/bts_rc/furniture/misc_healthstation2.mdl
models/bts_rc/furniture/misc_kitchenroll.mdl
models/bts_rc/furniture/misc_locker1.mdl
models/bts_rc/furniture/misc_machine.mdl
models/bts_rc/furniture/misc_map.mdl
models/bts_rc/furniture/misc_paper_rubbish.mdl
models/bts_rc/furniture/misc_powerbox.mdl
models/bts_rc/furniture/misc_printer.mdl
models/bts_rc/furniture/misc_propaganda1.mdl
models/bts_rc/furniture/misc_retina_repair.mdl
models/bts_rc/furniture/misc_sentryhouse_large.mdl
models/bts_rc/furniture/misc_sentryhouse_mini.mdl
models/bts_rc/furniture/misc_suitcharger1.mdl
models/bts_rc/furniture/misc_tablelamp.mdl
models/bts_rc/furniture/misc_taps.mdl
models/bts_rc/furniture/misc_techcomp1.mdl
models/bts_rc/furniture/misc_techcomp2.mdl
models/bts_rc/furniture/misc_techcomp3.mdl
models/bts_rc/furniture/misc_techcomp4.mdl
models/bts_rc/furniture/misc_techcomp5.mdl
models/bts_rc/furniture/misc_toolchest.mdl
models/bts_rc/furniture/misc_tv_hanging.mdl
models/bts_rc/furniture/misc_vendingmachine1.mdl
models/bts_rc/furniture/misc_vendingmachine2.mdl
models/bts_rc/furniture/misc_vendingmachine3.mdl
models/bts_rc/furniture/misc_vendingmachine4.mdl
models/bts_rc/furniture/misc_ventguard.mdl
models/bts_rc/furniture/misc_walkway.mdl
models/bts_rc/furniture/misc_wallcomp1.mdl
models/bts_rc/furniture/misc_wallcomp2.mdl
models/bts_rc/furniture/misc_wallcomp3.mdl
models/bts_rc/furniture/misc_wallcomp4.mdl
models/bts_rc/furniture/misc_wallcomp5.mdl
models/bts_rc/furniture/misc_watercooler.mdl
models/bts_rc/furniture/office_cabinet.mdl
models/bts_rc/furniture/office_cabinet2.mdl
models/bts_rc/furniture/office_cabinet3.mdl
models/bts_rc/furniture/office_cabinet4.mdl
models/bts_rc/furniture/office_computer1.mdl
models/bts_rc/furniture/office_computer2.mdl
models/bts_rc/furniture/office_computer3.mdl
models/bts_rc/furniture/office_partition.mdl
models/bts_rc/furniture/office_table.mdl
models/bts_rc/furniture/office_table_long.mdl
models/bts_rc/furniture/pallet_truck.mdl
models/bts_rc/furniture/paper_note1.mdl
models/bts_rc/furniture/paper_page1.mdl
models/bts_rc/furniture/paper_page2.mdl
models/bts_rc/furniture/paper_page3.mdl
models/bts_rc/furniture/paper_page4.mdl
models/bts_rc/furniture/paper_page5.mdl
models/bts_rc/furniture/pool_table.mdl
models/bts_rc/furniture/pushcart.mdl
models/bts_rc/furniture/radiotower.mdl
models/bts_rc/furniture/raptop.mdl
models/bts_rc/furniture/restroom_stalls.mdl
models/bts_rc/furniture/retina_component.mdl
models/bts_rc/furniture/security_console.mdl
models/bts_rc/furniture/shelf.mdl
models/bts_rc/furniture/shelf_short.mdl
models/bts_rc/furniture/sofa.mdl
models/bts_rc/furniture/storage_crate1.mdl
models/bts_rc/furniture/storage_crate2.mdl
models/bts_rc/furniture/storage_crate4.mdl
models/bts_rc/furniture/storage_crate5.mdl
models/bts_rc/furniture/storage_crate6.mdl
models/bts_rc/furniture/studycart.mdl
models/bts_rc/furniture/suv1.mdl
models/bts_rc/furniture/suv2.mdl
models/bts_rc/furniture/suv_fucked.mdl
models/bts_rc/furniture/table.mdl
models/bts_rc/furniture/terrain_cliffs1.mdl
models/bts_rc/furniture/terrain_cliffs2.mdl
models/bts_rc/furniture/terrain_cliffs3.mdl
models/bts_rc/furniture/terrain_cliffs4.mdl
models/bts_rc/furniture/terrain_cliffs5.mdl
models/bts_rc/furniture/tower.mdl
models/bts_rc/furniture/tram_bigdoor.mdl
models/bts_rc/furniture/trashcan.mdl
models/bts_rc/furniture/truck_army.mdl
models/bts_rc/furniture/truck_blackops.mdl
models/bts_rc/furniture/truck_research.mdl
models/bts_rc/furniture/tv.mdl
models/bts_rc/furniture/tv_unit.mdl
models/bts_rc/furniture/valve.mdl
models/bts_rc/furniture/vents_fan.mdl
models/bts_rc/furniture/w_flashlightbattery.mdl
models/bts_rc/furniture/w_wpndisplay.mdl
models/bts_rc/furniture/warehouse_shelf.mdl
models/bts_rc/furniture/wheelchair.mdl
models/bts_rc/furniture/wires1.mdl
models/bts_rc/furniture/xen_growth.mdl
models/bts_rc/furniture/xen_growth_large.mdl
models/bts_rc/items/card.mdl
models/bts_rc/items/garabumon_pelt.mdl
models/bts_rc/items/skeleton_guard.mdl
models/bts_rc/items/tool_box.mdl
models/bts_rc/items/w_antidote.mdl
models/bts_rc/items/w_medkits.mdl
models/bts_rc/items/w_suit.mdl
models/bts_rc/monsters/agrunt.mdl
models/bts_rc/monsters/baby_voltigore.mdl
models/bts_rc/monsters/barney.mdl
models/bts_rc/monsters/barney_hd.mdl
models/bts_rc/monsters/bullsquid.mdl
models/bts_rc/monsters/chumtoad.mdl
models/bts_rc/monsters/civ_paper_scientist.mdl
models/bts_rc/monsters/construction.mdl
models/bts_rc/monsters/gonome.mdl
models/bts_rc/monsters/gonome_barney.mdl
models/bts_rc/monsters/gonome_blackops.mdl
models/bts_rc/monsters/gonome_hev.mdl
models/bts_rc/monsters/gonome_soldier.mdl
models/bts_rc/monsters/gonome_worker.mdl
models/bts_rc/monsters/hassassin.mdl
models/bts_rc/monsters/hassassin_uzi.mdl
models/bts_rc/monsters/headcrab.mdl
models/bts_rc/monsters/headcrab2.mdl
models/bts_rc/monsters/headcrab_young.mdl
models/bts_rc/monsters/hgrunt.mdl
models/bts_rc/monsters/hgrunt_alt.mdl
models/bts_rc/monsters/hgrunt_medic.mdl
models/bts_rc/monsters/hgrunt_opfor.mdl
models/bts_rc/monsters/hgrunt_opfor_alt.mdl
models/bts_rc/monsters/hgrunt_torch.mdl
models/bts_rc/monsters/hgrunt_torch2.mdl
models/bts_rc/monsters/holo.mdl
models/bts_rc/monsters/houndeye.mdl
models/bts_rc/monsters/hwgrunt.mdl
models/bts_rc/monsters/HWRgrunt.mdl
models/bts_rc/monsters/islave.mdl
models/bts_rc/monsters/maintenance.mdl
models/bts_rc/monsters/maintenance2.mdl
models/bts_rc/monsters/massn.mdl
models/bts_rc/monsters/massn_medic.mdl
models/bts_rc/monsters/massn_opfor.mdl
models/bts_rc/monsters/osprey2_1.mdl
models/bts_rc/monsters/osprey2_1_BO.mdl
models/bts_rc/monsters/otis.mdl
models/bts_rc/monsters/otis2.mdl
models/bts_rc/monsters/pit_drone.mdl
models/bts_rc/monsters/rat.mdl
models/bts_rc/monsters/rgrunt.mdl
models/bts_rc/monsters/rgrunt_opfor.mdl
models/bts_rc/monsters/robothwgrunt.mdl
models/bts_rc/monsters/scientist.mdl
models/bts_rc/monsters/scientist_alt.mdl
models/bts_rc/monsters/scientist_alt2.mdl
models/bts_rc/monsters/scientist_classic.mdl
models/bts_rc/monsters/scientist_deadbody_v1.mdl
models/bts_rc/monsters/scientist_hd.mdl
models/bts_rc/monsters/scientist_hd2.mdl
models/bts_rc/monsters/scientist_hd3.mdl
models/bts_rc/monsters/sentry_blkops.mdl
models/bts_rc/monsters/sentry_blkopst.mdl
models/bts_rc/monsters/snapbug.mdl
models/bts_rc/monsters/snapbugattach.mdl
models/bts_rc/monsters/strooper.mdl
models/bts_rc/monsters/tor.mdl
models/bts_rc/monsters/tort_miniturret.mdl
models/bts_rc/monsters/tort_turret.mdl
models/bts_rc/monsters/worker.mdl
models/bts_rc/monsters/zombie.mdl
models/bts_rc/monsters/zombie_alt.mdl
models/bts_rc/monsters/zombie_barney.mdl
models/bts_rc/monsters/zombie_barney2.mdl
models/bts_rc/monsters/zombie_barney3.mdl
models/bts_rc/monsters/zombie_barney_alt.mdl
models/bts_rc/monsters/zombie_blackops.mdl
models/bts_rc/monsters/zombie_blackops2.mdl
models/bts_rc/monsters/zombie_blackops3.mdl
models/bts_rc/monsters/zombie_cleansuit.mdl
models/bts_rc/monsters/zombie_construction.mdl
models/bts_rc/monsters/zombie_construction2.mdl
models/bts_rc/monsters/zombie_construction_alt.mdl
models/bts_rc/monsters/zombie_construction_gus.mdl
models/bts_rc/monsters/zombie_construction_welder.mdl
models/bts_rc/monsters/zombie_curvy.mdl
models/bts_rc/monsters/zombie_engineer.mdl
models/bts_rc/monsters/zombie_engineer2.mdl
models/bts_rc/monsters/zombie_gus.mdl
models/bts_rc/monsters/zombie_hev.mdl
models/bts_rc/monsters/zombie_hev2.mdl
models/bts_rc/monsters/zombie_medic.mdl
models/bts_rc/monsters/zombie_otis.mdl
models/bts_rc/monsters/zombie_soldier.mdl
models/bts_rc/monsters/zombie_soldier2.mdl
models/bts_rc/monsters/zombie_soldier3.mdl
models/bts_rc/monsters/zombie_worker.mdl
models/bts_rc/monsters/zombie_worker2.mdl
models/bts_rc/null.mdl
models/bts_rc/ska/hgrunt.mdl
models/bts_rc/ska/hgruntf.mdl
models/bts_rc/weapons/barney_helmet.mdl
models/bts_rc/weapons/barney_vest.mdl
models/bts_rc/weapons/electro_bolt.mdl
models/bts_rc/weapons/flare.mdl
models/bts_rc/weapons/flaret.mdl
models/bts_rc/weapons/p_357.mdl
models/bts_rc/weapons/p_9mmar.mdl
models/bts_rc/weapons/p_9mmARGL.mdl
models/bts_rc/weapons/p_9mmhandgun.mdl
models/bts_rc/weapons/p_9mmhandgunsd.mdl
models/bts_rc/weapons/p_axe.mdl
models/bts_rc/weapons/p_beretta.mdl
models/bts_rc/weapons/p_broom.mdl
models/bts_rc/weapons/p_crossbow.mdl
models/bts_rc/weapons/p_crowbar.mdl
models/bts_rc/weapons/p_crowbarb.mdl
models/bts_rc/weapons/p_crowbaro.mdl
models/bts_rc/weapons/p_crowbary.mdl
models/bts_rc/weapons/p_desert_eagle.mdl
models/bts_rc/weapons/p_flame.mdl
models/bts_rc/weapons/p_flare.mdl
models/bts_rc/weapons/p_flaregun.mdl
models/bts_rc/weapons/p_flashlight.mdl
models/bts_rc/weapons/p_glock17f.mdl
models/bts_rc/weapons/p_glock18.mdl
models/bts_rc/weapons/p_m16.mdl
models/bts_rc/weapons/p_m16sd.mdl
models/bts_rc/weapons/p_m4.mdl
models/bts_rc/weapons/p_m40a1.mdl
models/bts_rc/weapons/p_m4sd.mdl
models/bts_rc/weapons/p_m79.mdl
models/bts_rc/weapons/p_medkit.mdl
models/bts_rc/weapons/p_pipe.mdl
models/bts_rc/weapons/p_pipe_wrench.mdl
models/bts_rc/weapons/p_poolstick.mdl
models/bts_rc/weapons/p_samr.mdl
models/bts_rc/weapons/p_saw.mdl
models/bts_rc/weapons/p_sawsd.mdl
models/bts_rc/weapons/p_sbshotgun.mdl
models/bts_rc/weapons/p_screwdriver.mdl
models/bts_rc/weapons/p_shotgun.mdl
models/bts_rc/weapons/p_sledgehammer.mdl
models/bts_rc/weapons/p_spanner.mdl
models/bts_rc/weapons/p_uzi.mdl
models/bts_rc/weapons/p_uzisd.mdl
models/bts_rc/weapons/saw_shell.mdl
models/bts_rc/weapons/v_357.mdl
models/bts_rc/weapons/v_9mmar.mdl
models/bts_rc/weapons/v_9mmARGL.mdl
models/bts_rc/weapons/v_9mmhandgun.mdl
models/bts_rc/weapons/v_9mmhandgunsd.mdl
models/bts_rc/weapons/v_axe.mdl
models/bts_rc/weapons/v_beretta.mdl
models/bts_rc/weapons/v_broom.mdl
models/bts_rc/weapons/v_crossbow.mdl
models/bts_rc/weapons/v_crowbar.mdl
models/bts_rc/weapons/v_crowbarb.mdl
models/bts_rc/weapons/v_crowbaro.mdl
models/bts_rc/weapons/v_crowbary.mdl
models/bts_rc/weapons/v_desert_eagle.mdl
models/bts_rc/weapons/v_fists.mdl
models/bts_rc/weapons/v_flame.mdl
models/bts_rc/weapons/v_flare.mdl
models/bts_rc/weapons/v_flaregun.mdl
models/bts_rc/weapons/v_flashlight.mdl
models/bts_rc/weapons/v_glock17f.mdl
models/bts_rc/weapons/v_glock18.mdl
models/bts_rc/weapons/v_grenade.mdl
models/bts_rc/weapons/v_knife.mdl
models/bts_rc/weapons/v_m16a2.mdl
models/bts_rc/weapons/v_m16a2sd.mdl
models/bts_rc/weapons/v_m4.mdl
models/bts_rc/weapons/v_m40a1.mdl
models/bts_rc/weapons/v_m4sd.mdl
models/bts_rc/weapons/v_m79.mdl
models/bts_rc/weapons/v_medkit.mdl
models/bts_rc/weapons/v_pipe.mdl
models/bts_rc/weapons/v_pipe_wrench.mdl
models/bts_rc/weapons/v_poolstick.mdl
models/bts_rc/weapons/v_samr.mdl
models/bts_rc/weapons/v_saw.mdl
models/bts_rc/weapons/v_sawsd.mdl
models/bts_rc/weapons/v_sbshotgun.mdl
models/bts_rc/weapons/v_screwdriver.mdl
models/bts_rc/weapons/v_shotgun.mdl
models/bts_rc/weapons/v_sledgehammer.mdl
models/bts_rc/weapons/v_spanner.mdl
models/bts_rc/weapons/v_uzi.mdl
models/bts_rc/weapons/v_uzisd.mdl
models/bts_rc/weapons/w_556nato.mdl
models/bts_rc/weapons/w_9mmar.mdl
models/bts_rc/weapons/w_9mmarclip.mdl
models/bts_rc/weapons/w_9mmarGL.mdl
models/bts_rc/weapons/w_9mmclip.mdl
models/bts_rc/weapons/w_9mmclip_falco.mdl
models/bts_rc/weapons/w_9mmhandgun.mdl
models/bts_rc/weapons/w_9mmhandgunsd.mdl
models/bts_rc/weapons/w_axe.mdl
models/bts_rc/weapons/w_battery.mdl
models/bts_rc/weapons/w_beretta.mdl
models/bts_rc/weapons/w_broom.mdl
models/bts_rc/weapons/w_crossbow.mdl
models/bts_rc/weapons/w_crossbow_clip.mdl
models/bts_rc/weapons/w_crowbar.mdl
models/bts_rc/weapons/w_crowbarb.mdl
models/bts_rc/weapons/w_crowbaro.mdl
models/bts_rc/weapons/w_crowbary.mdl
models/bts_rc/weapons/w_desert_eagle.mdl
models/bts_rc/weapons/w_flame.mdl
models/bts_rc/weapons/w_flare.mdl
models/bts_rc/weapons/w_flaregun.mdl
models/bts_rc/weapons/w_flaregun_clip.mdl
models/bts_rc/weapons/w_flaret.mdl
models/bts_rc/weapons/w_flashlight.mdl
models/bts_rc/weapons/w_glock17f.mdl
models/bts_rc/weapons/w_glock18.mdl
models/bts_rc/weapons/w_m16.mdl
models/bts_rc/weapons/w_m16sd.mdl
models/bts_rc/weapons/w_m4.mdl
models/bts_rc/weapons/w_m40a1.mdl
models/bts_rc/weapons/w_m4sd.mdl
models/bts_rc/weapons/w_m79.mdl
models/bts_rc/weapons/w_medkit.mdl
models/bts_rc/weapons/w_mp5_clip.mdl
models/bts_rc/weapons/w_pipe.mdl
models/bts_rc/weapons/w_pipe_wrench.mdl
models/bts_rc/weapons/w_pmedkit.mdl
models/bts_rc/weapons/w_poolstick.mdl
models/bts_rc/weapons/w_samr.mdl
models/bts_rc/weapons/w_saw.mdl
models/bts_rc/weapons/w_saw_clip.mdl
models/bts_rc/weapons/w_sawsd.mdl
models/bts_rc/weapons/w_sbshotgun.mdl
models/bts_rc/weapons/w_screwdriver.mdl
models/bts_rc/weapons/w_shotbox.mdl
models/bts_rc/weapons/w_shotgun.mdl
models/bts_rc/weapons/w_sledgehammer.mdl
models/bts_rc/weapons/w_spanner.mdl
models/bts_rc/weapons/w_tripmine.mdl
models/bts_rc/weapons/w_uzi.mdl
models/bts_rc/weapons/w_uzi_clip.mdl
models/bts_rc/weapons/w_uzisd.mdl
models/mikk/misc/bloodpuddle.mdl
models/player/bts_barney/bts_barney.bmp
models/player/bts_barney/bts_barney.mdl
models/player/bts_barney2/bts_barney2.bmp
models/player/bts_barney2/bts_barney2.mdl
models/player/bts_barney3/bts_barney3.bmp
models/player/bts_barney3/bts_barney3.mdl
models/player/bts_cleansuit/bts_cleansuit.bmp
models/player/bts_cleansuit/bts_cleansuit.mdl
models/player/bts_construction/bts_construction.bmp
models/player/bts_construction/bts_construction.mdl
models/player/bts_construction2/bts_construction2.bmp
models/player/bts_construction2/bts_construction2.mdl
models/player/bts_construction3/bts_construction3.bmp
models/player/bts_construction3/bts_construction3.mdl
models/player/bts_construction4/bts_construction4.bmp
models/player/bts_construction4/bts_construction4.mdl
models/player/bts_gus/bts_gus.bmp
models/player/bts_gus/bts_gus.mdl
models/player/bts_helmet/bts_helmet.bmp
models/player/bts_helmet/bts_helmet.mdl
models/player/bts_op/bts_op.bmp
models/player/bts_op/bts_op.mdl
models/player/bts_op2/bts_op2.bmp
models/player/bts_op2/bts_op2.mdl
models/player/bts_op3/bts_op3.bmp
models/player/bts_op3/bts_op3.mdl
models/player/bts_op4/bts_op4.bmp
models/player/bts_op4/bts_op4.mdl
models/player/bts_op5/bts_op5.bmp
models/player/bts_op5/bts_op5.mdl
models/player/bts_op6/bts_op6.bmp
models/player/bts_op6/bts_op6.mdl
models/player/bts_op_back/bts_op_back.bmp
models/player/bts_op_back/bts_op_back.mdl
models/player/bts_op_band/bts_op_band.bmp
models/player/bts_op_band/bts_op_band.mdl
models/player/bts_op_blop/bts_op_blop.bmp
models/player/bts_op_blop/bts_op_blop.mdl
models/player/bts_op_chud/bts_op_chud.bmp
models/player/bts_op_chud/bts_op_chud.mdl
models/player/bts_op_demo/bts_op_demo.bmp
models/player/bts_op_demo/bts_op_demo.mdl
models/player/bts_op_dual/bts_op_dual.bmp
models/player/bts_op_dual/bts_op_dual.mdl
models/player/bts_op_fat/bts_op_fat.bmp
models/player/bts_op_fat/bts_op_fat.mdl
models/player/bts_op_free/bts_op_free.bmp
models/player/bts_op_free/bts_op_free.mdl
models/player/bts_op_gus/bts_op_gus.bmp
models/player/bts_op_gus/bts_op_gus.mdl
models/player/bts_op_hgrunt/bts_op_hgrunt.bmp
models/player/bts_op_hgrunt/bts_op_hgrunt.mdl
models/player/bts_op_hurt/bts_op_hurt.bmp
models/player/bts_op_hurt/bts_op_hurt.mdl
models/player/bts_op_medic/bts_op_medic.bmp
models/player/bts_op_medic/bts_op_medic.mdl
models/player/bts_op_otis/bts_op_otis.bmp
models/player/bts_op_otis/bts_op_otis.mdl
models/player/bts_op_otis2/bts_op_otis2.bmp
models/player/bts_op_otis2/bts_op_otis2.mdl
models/player/bts_op_pissed/bts_op_pissed.bmp
models/player/bts_op_pissed/bts_op_pissed.mdl
models/player/bts_op_sigma/bts_op_sigma.bmp
models/player/bts_op_sigma/bts_op_sigma.mdl
models/player/bts_op_signal/bts_op_signal.bmp
models/player/bts_op_signal/bts_op_signal.mdl
models/player/bts_op_vet/bts_op_vet.bmp
models/player/bts_op_vet/bts_op_vet.mdl
models/player/bts_otis/bts_otis.bmp
models/player/bts_otis/bts_otis.mdl
models/player/bts_otis2/bts_otis2.bmp
models/player/bts_otis2/bts_otis2.mdl
models/player/bts_otis_blk/bts_otis_blk.bmp
models/player/bts_otis_blk/bts_otis_blk.mdl
models/player/bts_scientist/bts_scientist.bmp
models/player/bts_scientist/bts_scientist.mdl
models/player/bts_scientist2/bts_scientist2.bmp
models/player/bts_scientist2/bts_scientist2.mdl
models/player/bts_scientist3/bts_scientist3.bmp
models/player/bts_scientist3/bts_scientist3.mdl
models/player/bts_scientist4/bts_scientist4.bmp
models/player/bts_scientist4/bts_scientist4.mdl
models/player/bts_scientist5/bts_scientist5.bmp
models/player/bts_scientist5/bts_scientist5.mdl
models/player/bts_scientist6/bts_scientist6.bmp
models/player/bts_scientist6/bts_scientist6.mdl
models/player/bts_vet/bts_vet.bmp
models/player/bts_vet/bts_vet.mdl
models/snd/rock_L1.mdl
models/snd/rock_L2.mdl
models/sp_portal/construction.mdl
models/sp_portal/piranha.mdl
models/the303/domecam.mdl
scripts/maps/bts_rc/bts_rc_register.as
scripts/maps/bts_rc/entities/ammo.as
scripts/maps/bts_rc/entities/env_bloodpuddle.as
scripts/maps/bts_rc/entities/func_bts_recharger.as
scripts/maps/bts_rc/entities/items.as
scripts/maps/bts_rc/entities/point_checkpoint.as
scripts/maps/bts_rc/entities/randomizer.as
scripts/maps/bts_rc/entities/trigger_logger.as
scripts/maps/bts_rc/entities/trigger_update_class.as
scripts/maps/bts_rc/gamemodes/lasers.as
scripts/maps/bts_rc/gamemodes/player_voices.as
scripts/maps/bts_rc/Hooks/monster_killed.as
scripts/maps/bts_rc/Hooks/monster_takedamage.as
scripts/maps/bts_rc/Hooks/player_connect.as
scripts/maps/bts_rc/Hooks/player_takedamage.as
scripts/maps/bts_rc/Hooks/player_think.as
scripts/maps/bts_rc/monsters/custommonsters.as
scripts/maps/bts_rc/monsters/customMonsterSettings.as
scripts/maps/bts_rc/monsters/hwrgboss.as
scripts/maps/bts_rc/monsters/monster_snapbug.as
scripts/maps/bts_rc/monsters/monster_zombie_grenadier.as
scripts/maps/bts_rc/monsters/monster_zombie_gunner.as
scripts/maps/bts_rc/monsters/robogrunts.as
scripts/maps/bts_rc/monsters/zombies.as
scripts/maps/bts_rc/weapons/proj/flare.as
scripts/maps/bts_rc/weapons/proj/m79_rocket.as
scripts/maps/bts_rc/weapons/weapon_bts_axe.as
scripts/maps/bts_rc/weapons/weapon_bts_beretta.as
scripts/maps/bts_rc/weapons/weapon_bts_broom.as
scripts/maps/bts_rc/weapons/weapon_bts_crowbar.as
scripts/maps/bts_rc/weapons/weapon_bts_eagle.as
scripts/maps/bts_rc/weapons/weapon_bts_fists.as
scripts/maps/bts_rc/weapons/weapon_bts_flamethrower.as
scripts/maps/bts_rc/weapons/weapon_bts_flare.as
scripts/maps/bts_rc/weapons/weapon_bts_flaregun.as
scripts/maps/bts_rc/weapons/weapon_bts_flashlight.as
scripts/maps/bts_rc/weapons/weapon_bts_glock.as
scripts/maps/bts_rc/weapons/weapon_bts_glock17f.as
scripts/maps/bts_rc/weapons/weapon_bts_glock18.as
scripts/maps/bts_rc/weapons/weapon_bts_glocksd.as
scripts/maps/bts_rc/weapons/weapon_bts_handgrenade.as
scripts/maps/bts_rc/weapons/weapon_bts_knife.as
scripts/maps/bts_rc/weapons/weapon_bts_m16.as
scripts/maps/bts_rc/weapons/weapon_bts_m16sd.as
scripts/maps/bts_rc/weapons/weapon_bts_m4.as
scripts/maps/bts_rc/weapons/weapon_bts_m4sd.as
scripts/maps/bts_rc/weapons/weapon_bts_m79.as
scripts/maps/bts_rc/weapons/weapon_bts_medkit.as
scripts/maps/bts_rc/weapons/weapon_bts_mp5.as
scripts/maps/bts_rc/weapons/weapon_bts_mp5gl.as
scripts/maps/bts_rc/weapons/weapon_bts_pipe.as
scripts/maps/bts_rc/weapons/weapon_bts_pipewrench.as
scripts/maps/bts_rc/weapons/weapon_bts_poolstick.as
scripts/maps/bts_rc/weapons/weapon_bts_python.as
scripts/maps/bts_rc/weapons/weapon_bts_samr.as
scripts/maps/bts_rc/weapons/weapon_bts_saw.as
scripts/maps/bts_rc/weapons/weapon_bts_sawsd.as
scripts/maps/bts_rc/weapons/weapon_bts_sbshotgun.as
scripts/maps/bts_rc/weapons/weapon_bts_screwdriver.as
scripts/maps/bts_rc/weapons/weapon_bts_shotgun.as
scripts/maps/bts_rc/weapons/weapon_bts_sledgehammer.as
scripts/maps/bts_rc/weapons/weapon_bts_sniperrifle.as
scripts/maps/bts_rc/weapons/weapon_bts_spanner.as
scripts/maps/bts_rc/weapons/weapon_bts_uzi.as
scripts/maps/bts_rc/weapons/weapon_bts_uzisd.as
scripts/maps/bts_rc/weapons/weapon_bts_xbow.as
sound/bts_rc/agrunt/ag_pissed.wav
sound/bts_rc/ambience/36_VanHalen.ogg
sound/bts_rc/ambience/car_door.wav
sound/bts_rc/ambience/d0_bigwarning.wav
sound/bts_rc/ambience/d0_blast.wav
sound/bts_rc/ambience/d0_lightbang.wav
sound/bts_rc/ambience/d1_radio.wav
sound/bts_rc/ambience/d2_cranealarm.ogg
sound/bts_rc/ambience/d2_radio.ogg
sound/bts_rc/ambience/d3_radio.wav
sound/bts_rc/ambience/d3_setup.wav
sound/bts_rc/ambience/d4_radio.wav
sound/bts_rc/ambience/d4_water.wav
sound/bts_rc/ambience/d4_zombiehint.ogg
sound/bts_rc/ambience/d5_printer.wav
sound/bts_rc/ambience/d5_radio.wav
sound/bts_rc/ambience/d5_warning.wav
sound/bts_rc/ambience/hecu_ambience1.wav
sound/bts_rc/ambience/hecu_ambience2.wav
sound/bts_rc/ambience/hecu_ambience3.wav
sound/bts_rc/ambience/hecu_ambience4.wav
sound/bts_rc/ambience/hecu_ambience5.wav
sound/bts_rc/ambience/mechwhine_startup.wav
sound/bts_rc/ambience/mechwhine_stop.wav
sound/bts_rc/ambience/neigh.ogg
sound/bts_rc/ambience/osprey_lit.wav
sound/bts_rc/ambience/ospreyflyby.wav
sound/bts_rc/ambience/tv_noise1.wav
sound/bts_rc/ambience/tv_noise2.wav
sound/bts_rc/ambience/vent_ambience.wav
sound/bts_rc/ambience/wsam_warn.ogg
sound/bts_rc/barney/ba_a1hint.ogg
sound/bts_rc/barney/ba_alternative.ogg
sound/bts_rc/barney/ba_gears.ogg
sound/bts_rc/barney/ba_intro.ogg
sound/bts_rc/barney/ba_passaway.ogg
sound/bts_rc/barney/ba_passaway.wav
sound/bts_rc/blops_medic.txt
sound/bts_rc/construction.txt
sound/bts_rc/construction/con_armory.ogg
sound/bts_rc/construction/con_armory_alt.ogg
sound/bts_rc/construction/con_gears.ogg
sound/bts_rc/construction/con_keycard.ogg
sound/bts_rc/construction/ma_answer1.wav
sound/bts_rc/construction/ma_answer2.wav
sound/bts_rc/construction/ma_answer3.wav
sound/bts_rc/construction/ma_answer4.wav
sound/bts_rc/construction/ma_answer5.wav
sound/bts_rc/construction/ma_answer6.wav
sound/bts_rc/construction/ma_answer7.wav
sound/bts_rc/construction/ma_can.wav
sound/bts_rc/construction/ma_cant.wav
sound/bts_rc/construction/ma_codes.wav
sound/bts_rc/construction/ma_cure1.wav
sound/bts_rc/construction/ma_cure2.wav
sound/bts_rc/construction/ma_cure3.wav
sound/bts_rc/construction/ma_die1.wav
sound/bts_rc/construction/ma_die2.wav
sound/bts_rc/construction/ma_die3.wav
sound/bts_rc/construction/ma_greet.wav
sound/bts_rc/construction/ma_greet2.wav
sound/bts_rc/construction/ma_hear1.wav
sound/bts_rc/construction/ma_hear2.wav
sound/bts_rc/construction/ma_hear3.wav
sound/bts_rc/construction/ma_idle1.wav
sound/bts_rc/construction/ma_idle2.wav
sound/bts_rc/construction/ma_idle3.wav
sound/bts_rc/construction/ma_idle4.wav
sound/bts_rc/construction/ma_idle5.wav
sound/bts_rc/construction/ma_idle6.wav
sound/bts_rc/construction/ma_idle7.wav
sound/bts_rc/construction/ma_idle8.wav
sound/bts_rc/construction/ma_idle9.wav
sound/bts_rc/construction/ma_kill1.wav
sound/bts_rc/construction/ma_kill2.wav
sound/bts_rc/construction/ma_kill3.wav
sound/bts_rc/construction/ma_kill4.wav
sound/bts_rc/construction/ma_kill5.wav
sound/bts_rc/construction/ma_kill6.wav
sound/bts_rc/construction/ma_kill7.wav
sound/bts_rc/construction/ma_mad1.wav
sound/bts_rc/construction/ma_mad2.wav
sound/bts_rc/construction/ma_mad3.wav
sound/bts_rc/construction/ma_mad4.wav
sound/bts_rc/construction/ma_mad5.wav
sound/bts_rc/construction/ma_mad6.wav
sound/bts_rc/construction/ma_mortal.wav
sound/bts_rc/construction/ma_ok1.wav
sound/bts_rc/construction/ma_ok2.wav
sound/bts_rc/construction/ma_ok3.wav
sound/bts_rc/construction/ma_ok4.wav
sound/bts_rc/construction/ma_ok5.wav
sound/bts_rc/construction/ma_ok6.wav
sound/bts_rc/construction/ma_ok7.wav
sound/bts_rc/construction/ma_pain1.wav
sound/bts_rc/construction/ma_pain2.wav
sound/bts_rc/construction/ma_pain3.wav
sound/bts_rc/construction/ma_question1.wav
sound/bts_rc/construction/ma_question10.wav
sound/bts_rc/construction/ma_question11.wav
sound/bts_rc/construction/ma_question2.wav
sound/bts_rc/construction/ma_question3.wav
sound/bts_rc/construction/ma_question4.wav
sound/bts_rc/construction/ma_question5.wav
sound/bts_rc/construction/ma_question6.wav
sound/bts_rc/construction/ma_question7.wav
sound/bts_rc/construction/ma_question8.wav
sound/bts_rc/construction/ma_question9.wav
sound/bts_rc/construction/ma_scared1.wav
sound/bts_rc/construction/ma_scared2.wav
sound/bts_rc/construction/ma_shot1.wav
sound/bts_rc/construction/ma_shot2.wav
sound/bts_rc/construction/ma_shot3.wav
sound/bts_rc/construction/ma_shot4.wav
sound/bts_rc/construction/ma_smell1.wav
sound/bts_rc/construction/ma_smell2.wav
sound/bts_rc/construction/ma_smell3.wav
sound/bts_rc/construction/ma_stop1.wav
sound/bts_rc/construction/ma_stop2.wav
sound/bts_rc/construction/ma_stop3.wav
sound/bts_rc/construction/ma_stop4.wav
sound/bts_rc/construction/ma_stop5.wav
sound/bts_rc/construction/ma_stop6.wav
sound/bts_rc/construction/ma_wound1.wav
sound/bts_rc/construction/ma_wound2.wav
sound/bts_rc/fgrunt/allied_announce.ogg
sound/bts_rc/fgrunt/d0_nightvision.wav
sound/bts_rc/fgrunt/d2_grunts_warn1.ogg
sound/bts_rc/fgrunt/d2_grunts_warn2.ogg
sound/bts_rc/fgrunt/d2_grunts_warn3.ogg
sound/bts_rc/fgrunt/d2_grunts_warn4.ogg
sound/bts_rc/fgrunt/d2_grunts_warn5.ogg
sound/bts_rc/fgrunt/gr_area1.wav
sound/bts_rc/fgrunt/gr_area2.wav
sound/bts_rc/fgrunt/gr_area3.wav
sound/bts_rc/fgrunt/gr_area4.wav
sound/bts_rc/fgrunt/gr_area5.wav
sound/bts_rc/fgrunt/gr_breach_main.wav
sound/bts_rc/fgrunt/gr_breach_sec.wav
sound/bts_rc/fgrunt/gr_d3tor.wav
sound/bts_rc/fgrunt/gr_powerback.wav
sound/bts_rc/fgrunt/gr_trips.wav
sound/bts_rc/fgrunt/gr_zombiehint.wav
sound/bts_rc/fgrunt/hg_m203.wav
sound/bts_rc/fgrunt/hg_m203_alt.wav
sound/bts_rc/fgrunt/medic_give_shot.wav
sound/bts_rc/fgrunt/sandbags.wav
sound/bts_rc/fgrunt/securitysystem.wav
sound/bts_rc/fgrunt/sentryup.wav
sound/bts_rc/fgrunt/suppliesup.wav
sound/bts_rc/fgrunt/torch_cut.wav
sound/bts_rc/fmbw.ogg
sound/bts_rc/fvox/hev_logon.wav
sound/bts_rc/gonome_hecu.txt
sound/bts_rc/gonome_hecu/gonome_idle1.wav
sound/bts_rc/gonome_hecu/gonome_idle2.wav
sound/bts_rc/gonome_hecu/gonome_idle3.wav
sound/bts_rc/gonome_hev.txt
sound/bts_rc/gonome_hev/gonome_death2.ogg
sound/bts_rc/gonome_hev/gonome_death3.ogg
sound/bts_rc/gonome_hev/gonome_death4.ogg
sound/bts_rc/gonome_hev/gonome_eat.ogg
sound/bts_rc/gonome_hev/gonome_idle1.ogg
sound/bts_rc/gonome_hev/gonome_idle2.ogg
sound/bts_rc/gonome_hev/gonome_idle3.ogg
sound/bts_rc/gonome_hev/gonome_melee1.ogg
sound/bts_rc/gonome_hev/gonome_melee2.ogg
sound/bts_rc/gonome_hev/gonome_pain1.ogg
sound/bts_rc/gonome_hev/gonome_pain2.ogg
sound/bts_rc/gonome_hev/gonome_pain3.ogg
sound/bts_rc/gonome_hev/gonome_pain4.ogg
sound/bts_rc/gonome_hev/gonome_step1.ogg
sound/bts_rc/gonome_hev/gonome_step2.ogg
sound/bts_rc/gonome_hev/gonome_throw.ogg
sound/bts_rc/holo/tr_holo_medpun.ogg
sound/bts_rc/holo/tr_holo_simulation.ogg
sound/bts_rc/holo/tr_holo_tortured.ogg
sound/bts_rc/holo/tr_holo_tortured2.ogg
sound/bts_rc/interference.ogg
sound/bts_rc/interference2.ogg
sound/bts_rc/items/9mmclip1.wav
sound/bts_rc/items/9mmclip2.wav
sound/bts_rc/items/9mmcock3.wav
sound/bts_rc/items/armor_pickup1.wav
sound/bts_rc/items/barrier.wav
sound/bts_rc/items/battery_pickup1.wav
sound/bts_rc/items/battery_reload.wav
sound/bts_rc/items/cleansuit_on.wav
sound/bts_rc/items/d3_sink.wav
sound/bts_rc/items/mag_flip.wav
sound/bts_rc/items/medcharge4.wav
sound/bts_rc/items/medshotno1.wav
sound/bts_rc/items/nvg_off.wav
sound/bts_rc/items/nvg_on.wav
sound/bts_rc/items/power_fail.wav
sound/bts_rc/items/power_online.wav
sound/bts_rc/items/repair_snd1.wav
sound/bts_rc/items/repair_snd2.wav
sound/bts_rc/items/repair_snd3.wav
sound/bts_rc/items/repair_snd4.wav
sound/bts_rc/items/repair_snd5.wav
sound/bts_rc/items/sprayaid1.wav
sound/bts_rc/items/suitcharge1.wav
sound/bts_rc/keller/dk_control.wav
sound/bts_rc/keller/dk_explain.wav
sound/bts_rc/massn.txt
sound/bts_rc/meme.ogg
sound/bts_rc/music/bts_rc_alienshock.ogg
sound/bts_rc/music/bts_rc_checkpoint.ogg
sound/bts_rc/music/bts_rc_credits.ogg
sound/bts_rc/music/bts_rc_credits_alt.ogg
sound/bts_rc/music/bts_rc_credits_alt2.ogg
sound/bts_rc/music/bts_rc_credits_alt3.ogg
sound/bts_rc/music/bts_rc_intro.ogg
sound/bts_rc/music/bts_vr_load.wav
sound/bts_rc/music/consequences.ogg
sound/bts_rc/music/Enforce_Protocol.ogg
sound/bts_rc/music/hb_fucked.wav
sound/bts_rc/music/hb_pass.ogg
sound/bts_rc/music/hb_vote.ogg
sound/bts_rc/music/Hostiles_Detected.ogg
sound/bts_rc/music/Military_dread.ogg
sound/bts_rc/music/Operators_Dread.ogg
sound/bts_rc/music/resonance.ogg
sound/bts_rc/music/sewers.ogg
sound/bts_rc/music/Wishful_Forces.ogg
sound/bts_rc/null.wav
sound/bts_rc/ops/d0_targets.wav
sound/bts_rc/ops/ops_advance.wav
sound/bts_rc/ops/ops_alert1.ogg
sound/bts_rc/ops/ops_clear1.ogg
sound/bts_rc/ops/ops_flank.wav
sound/bts_rc/ops/ops_idle1.ogg
sound/bts_rc/ops/ops_idle2.ogg
sound/bts_rc/ops/ops_idle3.ogg
sound/bts_rc/ops/ops_kill1.wav
sound/bts_rc/ops/ops_med_fwound.wav
sound/bts_rc/ops/ops_med_notime.wav
sound/bts_rc/ops/ops_med_onepiece.wav
sound/bts_rc/ops/ops_med_sting.wav
sound/bts_rc/otis/ot_poke1.wav
sound/bts_rc/otis/ot_poke2.wav
sound/bts_rc/otis/ot_poke3.wav
sound/bts_rc/otis/ot_poke4.wav
sound/bts_rc/player/cleansuit/cl_death1.wav
sound/bts_rc/player/cleansuit/cl_death2.wav
sound/bts_rc/player/cleansuit/cl_death3.wav
sound/bts_rc/player/cleansuit/cl_death4.wav
sound/bts_rc/player/cleansuit/cl_pain1.wav
sound/bts_rc/player/cleansuit/cl_pain2.wav
sound/bts_rc/player/cleansuit/cl_pain3.wav
sound/bts_rc/player/cleansuit/cl_pain4.wav
sound/bts_rc/player/cleansuit/cl_pain5.wav
sound/bts_rc/player/construction/co_die1.wav
sound/bts_rc/player/construction/co_die2.wav
sound/bts_rc/player/construction/co_die3.wav
sound/bts_rc/player/construction/co_die4.wav
sound/bts_rc/player/construction/co_pain1.wav
sound/bts_rc/player/construction/co_pain2.wav
sound/bts_rc/player/construction/co_pain3.wav
sound/bts_rc/player/construction/co_pain4.wav
sound/bts_rc/player/helmet/hm_death1.wav
sound/bts_rc/player/helmet/hm_death2.wav
sound/bts_rc/player/helmet/hm_death3.wav
sound/bts_rc/player/helmet/hm_death4.wav
sound/bts_rc/player/helmet/hm_pain1.wav
sound/bts_rc/player/helmet/hm_pain2.wav
sound/bts_rc/player/helmet/hm_pain3.wav
sound/bts_rc/player/helmet/hm_pain4.wav
sound/bts_rc/player/helmet/hm_pain5.wav
sound/bts_rc/rgas.ogg
sound/bts_rc/rgrunt/rb_alert1.wav
sound/bts_rc/rgrunt/rb_alert2.wav
sound/bts_rc/rgrunt/rb_alert3.wav
sound/bts_rc/rgrunt/rb_bo.wav
sound/bts_rc/rgrunt/rb_check1.wav
sound/bts_rc/rgrunt/rb_check2.wav
sound/bts_rc/rgrunt/rb_clear1.wav
sound/bts_rc/rgrunt/rb_clear2.wav
sound/bts_rc/rgrunt/rb_d4.wav
sound/bts_rc/rgrunt/rb_death1.wav
sound/bts_rc/rgrunt/rb_death2.wav
sound/bts_rc/rgrunt/rb_flof1.wav
sound/bts_rc/rgrunt/rb_flof2.wav
sound/bts_rc/rgrunt/rb_flof3.wav
sound/bts_rc/rgrunt/rb_gren1.wav
sound/bts_rc/rgrunt/rb_gren2.wav
sound/bts_rc/rgrunt/rbhw_deploy.wav
sound/bts_rc/rgrunt/rbhw_inbound.wav
sound/bts_rc/rgrunt/rbhw_melee1.wav
sound/bts_rc/rgrunt/rbhw_shield.wav
sound/bts_rc/rgrunt/rbhw_shield2.wav
sound/bts_rc/rgrunt/rbhw_shield_smash.ogg
sound/bts_rc/rgrunt/rbhw_step1.wav
sound/bts_rc/rgrunt/rbhw_step2.wav
sound/bts_rc/rgrunt/rg_alert1.wav
sound/bts_rc/rgrunt/rg_hurt1.wav
sound/bts_rc/rgrunt/rg_hurt2.wav
sound/bts_rc/rgrunt/rg_hurt3.wav
sound/bts_rc/rgrunt/rg_step1.wav
sound/bts_rc/rgrunt/rg_step2.wav
sound/bts_rc/rgrunt/rhw_idle2.wav
sound/bts_rc/rgrunt_opfor.txt
sound/bts_rc/rgrunts.txt
sound/bts_rc/scientist/sc_area12.wav
sound/bts_rc/scientist/sc_area45.wav
sound/bts_rc/scientist/sci_adminroom.wav
sound/bts_rc/scientist/sci_d2_doors.wav
sound/bts_rc/scientist/sci_damn.wav
sound/bts_rc/scientist/sci_end.wav
sound/bts_rc/scientist/sci_foreshadow1.wav
sound/bts_rc/scientist/sci_foreshadow2.wav
sound/bts_rc/scientist/sci_foreshadow3.wav
sound/bts_rc/scientist/sci_foreshadow4.wav
sound/bts_rc/scientist/sci_foreshadow5.wav
sound/bts_rc/scientist/sci_interferance.wav
sound/bts_rc/scientist/sci_intro.wav
sound/bts_rc/scientist/sci_intro2.wav
sound/bts_rc/scientist/sci_keyitems.wav
sound/bts_rc/scientist/sci_labhint.wav
sound/bts_rc/scientist/sci_lockdown.wav
sound/bts_rc/scientist/sci_poke1.wav
sound/bts_rc/scientist/sci_poke2.wav
sound/bts_rc/scientist/sci_poke3.wav
sound/bts_rc/scientist/sci_sample.wav
sound/bts_rc/scientist/sci_simulation.wav
sound/bts_rc/scientist/sci_situation.wav
sound/bts_rc/scientist/sci_sorry.wav
sound/bts_rc/scientist/sci_upgradehint.wav
sound/bts_rc/scientist/sci_volume.wav
sound/bts_rc/scientist/test1.wav
sound/bts_rc/sentry/tu_deploy.wav
sound/bts_rc/sentry/tu_die.wav
sound/bts_rc/sentry/tu_die2.wav
sound/bts_rc/sentry/tu_die3.wav
sound/bts_rc/sentry/tu_fire1.wav
sound/bts_rc/sentry/tu_ping.wav
sound/bts_rc/sentry_blackops.txt
sound/bts_rc/snapbug/sb_alert3.wav
sound/bts_rc/snapbug/sb_attack1.wav
sound/bts_rc/snapbug/sb_attack2.wav
sound/bts_rc/snapbug/sb_die1.wav
sound/bts_rc/snapbug/sb_die2.wav
sound/bts_rc/snapbug/sb_idle1.wav
sound/bts_rc/snapbug/sb_idle2.wav
sound/bts_rc/snapbug/sb_pain1.wav
sound/bts_rc/snapbug/sb_pain2.wav
sound/bts_rc/stepsounds/aslave_step1.wav
sound/bts_rc/stepsounds/aslave_step2.wav
sound/bts_rc/stepsounds/bull_step1.wav
sound/bts_rc/stepsounds/bull_step2.wav
sound/bts_rc/stepsounds/bull_step3.wav
sound/bts_rc/stepsounds/bull_step4.wav
sound/bts_rc/stepsounds/bvoltigore_footstep1.wav
sound/bts_rc/stepsounds/bvoltigore_footstep2.wav
sound/bts_rc/stepsounds/bvoltigore_footstep3.wav
sound/bts_rc/stepsounds/chum_attk.wav
sound/bts_rc/stepsounds/chum_ow.wav
sound/bts_rc/stepsounds/chum_slam.wav
sound/bts_rc/stepsounds/chum_step.wav
sound/bts_rc/stepsounds/crab_step1.wav
sound/bts_rc/stepsounds/crab_step2.wav
sound/bts_rc/stepsounds/crab_step3.wav
sound/bts_rc/stepsounds/crab_step4.wav
sound/bts_rc/stepsounds/gonome_step1.wav
sound/bts_rc/stepsounds/gonome_step2.wav
sound/bts_rc/stepsounds/gonome_step3.wav
sound/bts_rc/stepsounds/gonome_step4.wav
sound/bts_rc/stepsounds/hound_step1.wav
sound/bts_rc/stepsounds/hound_step2.wav
sound/bts_rc/stepsounds/hound_step3.wav
sound/bts_rc/stepsounds/hound_step4.wav
sound/bts_rc/stepsounds/pd_step1.wav
sound/bts_rc/stepsounds/pd_step2.wav
sound/bts_rc/stepsounds/pd_step3.wav
sound/bts_rc/stepsounds/pd_step4.wav
sound/bts_rc/stepsounds/shock_step1.wav
sound/bts_rc/stepsounds/shock_step2.wav
sound/bts_rc/stepsounds/shock_step3.wav
sound/bts_rc/stepsounds/shock_step4.wav
sound/bts_rc/tride/a1_arrive.ogg
sound/bts_rc/tride/a1_inbound.ogg
sound/bts_rc/tride/a4_arrive.ogg
sound/bts_rc/tride/a4_inbound.ogg
sound/bts_rc/tride/tr_announcement2.ogg
sound/bts_rc/tride/tr_announcement3.ogg
sound/bts_rc/tride/tr_announcement4.ogg
sound/bts_rc/tride/tr_announcement5.ogg
sound/bts_rc/tride/tr_arriving.ogg
sound/bts_rc/tride/tr_fucked.ogg
sound/bts_rc/tride/tr_leaving.ogg
sound/bts_rc/tride/tr_shutdown.ogg
sound/bts_rc/ts4e.ogg
sound/bts_rc/vox/blackops_announcement.ogg
sound/bts_rc/vox/blackops_sentrychange.ogg
sound/bts_rc/vox/d0_powerback.ogg
sound/bts_rc/vox/d0_tr_fucked.ogg
sound/bts_rc/vox/d0_tr_unfucked.ogg
sound/bts_rc/vox/d0_warning.ogg
sound/bts_rc/vox/d1_lockdown_offline.ogg
sound/bts_rc/vox/d1_lockdown_online.ogg
sound/bts_rc/vox/d1_retina.ogg
sound/bts_rc/vox/d1_retina_fail.ogg
sound/bts_rc/vox/d1_sentries_offline.ogg
sound/bts_rc/vox/d1_sentries_online.ogg
sound/bts_rc/vox/d1d4_tram_online.ogg
sound/bts_rc/vox/d2_generatorpwr.ogg
sound/bts_rc/vox/d2_generatorpwr2.ogg
sound/bts_rc/vox/d3_bridge.ogg
sound/bts_rc/vox/d3_power_off.ogg
sound/bts_rc/vox/d3_power_on.ogg
sound/bts_rc/vox/d4_chemical.ogg
sound/bts_rc/vox/d4_lockdown_online.ogg
sound/bts_rc/vox/intro.ogg
sound/bts_rc/vox/military_announcement.ogg
sound/bts_rc/vox/military_sentrychange.ogg
sound/bts_rc/vox/rgrunts_announcement.ogg
sound/bts_rc/vox/rgrunts_sentrychange.ogg
sound/bts_rc/weapons/9mm_clip.wav
sound/bts_rc/weapons/9mm_clipout.wav
sound/bts_rc/weapons/9mm_cock1.wav
sound/bts_rc/weapons/9mm_cock2.wav
sound/bts_rc/weapons/9mm_draw.wav
sound/bts_rc/weapons/9mm_in.wav
sound/bts_rc/weapons/axe_hit1.wav
sound/bts_rc/weapons/axe_hit2.wav
sound/bts_rc/weapons/axe_hitbod1.wav
sound/bts_rc/weapons/axe_hitbod2.wav
sound/bts_rc/weapons/axe_hitbod3.wav
sound/bts_rc/weapons/axe_miss1.wav
sound/bts_rc/weapons/beretta_draw.wav
sound/bts_rc/weapons/beretta_fire1.wav
sound/bts_rc/weapons/cbar_draw.wav
sound/bts_rc/weapons/desert_eagle_reload.wav
sound/bts_rc/weapons/desert_eagle_sup.wav
sound/bts_rc/weapons/fidget1.wav
sound/bts_rc/weapons/fidget_2.wav
sound/bts_rc/weapons/fidget_3.wav
sound/bts_rc/weapons/fidget_4.wav
sound/bts_rc/weapons/flare_bounce.wav
sound/bts_rc/weapons/flare_deploy.wav
sound/bts_rc/weapons/flare_on.wav
sound/bts_rc/weapons/flare_pickup.wav
sound/bts_rc/weapons/flare_pinpull.wav
sound/bts_rc/weapons/flaregun_draw.wav
sound/bts_rc/weapons/flaregun_reload1.wav
sound/bts_rc/weapons/flaregun_reload2.wav
sound/bts_rc/weapons/flaregun_shellin.wav
sound/bts_rc/weapons/flaregun_shellout.wav
sound/bts_rc/weapons/flaregun_shot1.wav
sound/bts_rc/weapons/flarehit1.wav
sound/bts_rc/weapons/flarehitbod1.wav
sound/bts_rc/weapons/flashlight_hit1.wav
sound/bts_rc/weapons/flashlight_hit2.wav
sound/bts_rc/weapons/flashlight_hitbod1.wav
sound/bts_rc/weapons/flashlight_hitbod2.wav
sound/bts_rc/weapons/flashlight_hitbod3.wav
sound/bts_rc/weapons/flashlight_miss1.wav
sound/bts_rc/weapons/flmfire2.wav
sound/bts_rc/weapons/flmgrexp.wav
sound/bts_rc/weapons/glock18_fire1.wav
sound/bts_rc/weapons/glock_fire1.wav
sound/bts_rc/weapons/glocksd_fire1.wav
sound/bts_rc/weapons/glocksd_fire2.wav
sound/bts_rc/weapons/grenade_draw.wav
sound/bts_rc/weapons/grenade_pinpull.wav
sound/bts_rc/weapons/grenade_throw1.wav
sound/bts_rc/weapons/grenade_throw2.wav
sound/bts_rc/weapons/gun_fire4.wav
sound/bts_rc/weapons/m16_burst1.wav
sound/bts_rc/weapons/m16_fire1.wav
sound/bts_rc/weapons/m16sd_burst1.wav
sound/bts_rc/weapons/m203_close.wav
sound/bts_rc/weapons/m203_in.wav
sound/bts_rc/weapons/m203_open.wav
sound/bts_rc/weapons/m203_shell.wav
sound/bts_rc/weapons/m4_clic1.wav
sound/bts_rc/weapons/m4_clipinsert1.wav
sound/bts_rc/weapons/m4_cliprelease1.wav
sound/bts_rc/weapons/m4_fire1.wav
sound/bts_rc/weapons/m4sd_fire1.wav
sound/bts_rc/weapons/m79_aimon.wav
sound/bts_rc/weapons/m79_close.wav
sound/bts_rc/weapons/m79_fire.wav
sound/bts_rc/weapons/m79_open.wav
sound/bts_rc/weapons/m79_shellin.wav
sound/bts_rc/weapons/m79_shellout.wav
sound/bts_rc/weapons/mp5_clip.wav
sound/bts_rc/weapons/mp5_clipout.wav
sound/bts_rc/weapons/mp5_draw.wav
sound/bts_rc/weapons/mp5_draw2.wav
sound/bts_rc/weapons/mp5_fire1.wav
sound/bts_rc/weapons/mp5_fire2.wav
sound/bts_rc/weapons/mp5_fire3.wav
sound/bts_rc/weapons/mp5_in.wav
sound/bts_rc/weapons/mp5_slap.wav
sound/bts_rc/weapons/pipe_hit1.wav
sound/bts_rc/weapons/pipe_hit2.wav
sound/bts_rc/weapons/pipe_hitbod1.wav
sound/bts_rc/weapons/pipe_hitbod2.wav
sound/bts_rc/weapons/pipe_hitbod3.wav
sound/bts_rc/weapons/pipe_miss1.wav
sound/bts_rc/weapons/reload1.wav
sound/bts_rc/weapons/reload3.wav
sound/bts_rc/weapons/saw_fire1.wav
sound/bts_rc/weapons/saw_reload.wav
sound/bts_rc/weapons/saw_reload2.wav
sound/bts_rc/weapons/sbscock1.wav
sound/bts_rc/weapons/sbshotgun_fire1.wav
sound/bts_rc/weapons/sd_hit1.wav
sound/bts_rc/weapons/sd_hit2.wav
sound/bts_rc/weapons/sd_hitbod1.wav
sound/bts_rc/weapons/sd_hitbod2.wav
sound/bts_rc/weapons/sd_hitbod3.wav
sound/bts_rc/weapons/sd_miss1.wav
sound/bts_rc/weapons/sledge_hit1.wav
sound/bts_rc/weapons/sledge_hit2.wav
sound/bts_rc/weapons/sledge_hitwall1.wav
sound/bts_rc/weapons/sledge_hitwall2.wav
sound/bts_rc/weapons/sledge_miss1.wav
sound/bts_rc/weapons/sledge_miss2.wav
sound/bts_rc/weapons/sniper_bolt1.wav
sound/bts_rc/weapons/sniper_bolt2.wav
sound/bts_rc/weapons/sniper_reload_first_seq.wav
sound/bts_rc/weapons/spas12_dbarrel1.wav
sound/bts_rc/weapons/uzi_fire1.wav
sound/bts_rc/weapons/xbow_bolt.wav
sound/bts_rc/weapons/xbow_draw2.wav
sound/bts_rc/weapons/xbow_fidget2.wav
sound/bts_rc/weapons/xbow_fire1.ogg
sound/bts_rc/weapons/xbow_fire1.wav
sound/bts_rc/weapons/xbow_hit1.wav
sound/bts_rc/weapons/xbow_hitbod1.wav
sound/bts_rc/weapons/xbow_hitbod2.wav
sound/bts_rc/weapons/xbow_magin.wav
sound/bts_rc/weapons/xbow_magready.wav
sound/bts_rc/zombie/zo_death1.wav
sound/bts_rc/zombie/zo_death2.wav
sound/bts_rc/zombie/zo_death3.wav
sound/bts_rc/zombie/zo_growl.wav
sound/bts_rc/zombie_hev.txt
sound/bts_rc/zombie_hev/zo_alert10.wav
sound/bts_rc/zombie_hev/zo_alert20.wav
sound/bts_rc/zombie_hev/zo_alert30.wav
sound/bts_rc/zombie_hev/zo_attack1.wav
sound/bts_rc/zombie_hev/zo_attack2.wav
sound/bts_rc/zombie_hev/zo_death1.wav
sound/bts_rc/zombie_hev/zo_death2.wav
sound/bts_rc/zombie_hev/zo_death3.wav
sound/bts_rc/zombie_hev/zo_idle1.wav
sound/bts_rc/zombie_hev/zo_idle2.wav
sound/bts_rc/zombie_hev/zo_idle3.wav
sound/bts_rc/zombie_hev/zo_idle4.wav
sound/bts_rc/zombie_hev/zo_pain1.wav
sound/bts_rc/zombie_hev/zo_pain2.wav
sound/bts_rc/zombie_runner.txt
sprites/bts_rc/640hudof01.spr
sprites/bts_rc/640hudof02.spr
sprites/bts_rc/ablood_1.spr
sprites/bts_rc/ablood_2.spr
sprites/bts_rc/ablood_3.spr
sprites/bts_rc/ablood_4.spr
sprites/bts_rc/ablood_5.spr
sprites/bts_rc/ammo_battery.spr
sprites/bts_rc/ammo_flare.spr
sprites/bts_rc/bts_desc_eng.spr
sprites/bts_rc/bts_desc_medium.spr
sprites/bts_rc/bts_desc_opr.spr
sprites/bts_rc/bts_desc_punished.spr
sprites/bts_rc/bts_desc_relaxed.spr
sprites/bts_rc/bts_desc_sci.spr
sprites/bts_rc/bts_desc_sec.spr
sprites/bts_rc/bts_desc_story.spr
sprites/bts_rc/bts_desc_tortured.spr
sprites/bts_rc/bts_rc_snapbug.spr
sprites/bts_rc/falcohead.spr
sprites/bts_rc/falcospin.spr
sprites/bts_rc/flare_selection.spr
sprites/bts_rc/fthrow.spr
sprites/bts_rc/gametitle.spr
sprites/bts_rc/Gauna_was_here_v2.spr
sprites/bts_rc/glock17f.spr
sprites/bts_rc/hblood_1.spr
sprites/bts_rc/hblood_2.spr
sprites/bts_rc/hblood_3.spr
sprites/bts_rc/inv_card_maint.spr
sprites/bts_rc/inv_card_research.spr
sprites/bts_rc/inv_card_security.spr
sprites/bts_rc/m4sd.spr
sprites/bts_rc/M79_crosshair.spr
sprites/bts_rc/mossberg.spr
sprites/bts_rc/mp5.spr
sprites/bts_rc/mp5gl.spr
sprites/bts_rc/muzzleflash12.spr
sprites/bts_rc/objectives/Armory.spr
sprites/bts_rc/objectives/obj_gear.spr
sprites/bts_rc/objectives/obj_gear_c1.spr
sprites/bts_rc/objectives/obj_gear_c2.spr
sprites/bts_rc/objectives/obj_gear_c3.spr
sprites/bts_rc/objectives/obj_gear_c4.spr
sprites/bts_rc/objectives/objective1.spr
sprites/bts_rc/objectives/objective10.spr
sprites/bts_rc/objectives/objective11.spr
sprites/bts_rc/objectives/objective2.spr
sprites/bts_rc/objectives/objective3.spr
sprites/bts_rc/objectives/objective4.spr
sprites/bts_rc/objectives/objective5.spr
sprites/bts_rc/objectives/objective6.spr
sprites/bts_rc/objectives/objective7.spr
sprites/bts_rc/objectives/objective8.spr
sprites/bts_rc/objectives/objective9.spr
sprites/bts_rc/opaqueexplode02.spr
sprites/bts_rc/screwd.spr
sprites/bts_rc/tfchud07.spr
sprites/bts_rc/w_beretta.spr
sprites/bts_rc/w_flare.spr
sprites/bts_rc/w_glocksd1.spr
sprites/bts_rc/w_glocksd4.spr
sprites/bts_rc/weapon_broom.spr
sprites/bts_rc/weapon_knife.spr
sprites/bts_rc/weapon_M79.spr
sprites/bts_rc/weapons/weapon_bts_axe.txt
sprites/bts_rc/weapons/weapon_bts_beretta.txt
sprites/bts_rc/weapons/weapon_bts_broom.txt
sprites/bts_rc/weapons/weapon_bts_crowbar.txt
sprites/bts_rc/weapons/weapon_bts_eagle.txt
sprites/bts_rc/weapons/weapon_bts_fists.txt
sprites/bts_rc/weapons/weapon_bts_flamethrower.txt
sprites/bts_rc/weapons/weapon_bts_flare.txt
sprites/bts_rc/weapons/weapon_bts_flaregun.txt
sprites/bts_rc/weapons/weapon_bts_flashlight.txt
sprites/bts_rc/weapons/weapon_bts_glock.txt
sprites/bts_rc/weapons/weapon_bts_glock17f.txt
sprites/bts_rc/weapons/weapon_bts_glock18.txt
sprites/bts_rc/weapons/weapon_bts_glocksd.txt
sprites/bts_rc/weapons/weapon_bts_handgrenade.txt
sprites/bts_rc/weapons/weapon_bts_knife.txt
sprites/bts_rc/weapons/weapon_bts_m16.txt
sprites/bts_rc/weapons/weapon_bts_m16sd.txt
sprites/bts_rc/weapons/weapon_bts_m4.txt
sprites/bts_rc/weapons/weapon_bts_m4sd.txt
sprites/bts_rc/weapons/weapon_bts_m79.txt
sprites/bts_rc/weapons/weapon_bts_medkit.txt
sprites/bts_rc/weapons/weapon_bts_mp5.txt
sprites/bts_rc/weapons/weapon_bts_mp5gl.txt
sprites/bts_rc/weapons/weapon_bts_pipe.txt
sprites/bts_rc/weapons/weapon_bts_pipewrench.txt
sprites/bts_rc/weapons/weapon_bts_poolstick.txt
sprites/bts_rc/weapons/weapon_bts_python.txt
sprites/bts_rc/weapons/weapon_bts_samr.txt
sprites/bts_rc/weapons/weapon_bts_saw.txt
sprites/bts_rc/weapons/weapon_bts_sawsd.txt
sprites/bts_rc/weapons/weapon_bts_sbshotgun.txt
sprites/bts_rc/weapons/weapon_bts_screwdriver.txt
sprites/bts_rc/weapons/weapon_bts_shotgun.txt
sprites/bts_rc/weapons/weapon_bts_sledgehammer.txt
sprites/bts_rc/weapons/weapon_bts_spanner.txt
sprites/bts_rc/weapons/weapon_bts_uzi.txt
sprites/bts_rc/weapons/weapon_bts_uzisd.txt
sprites/bts_rc/weapons/weapon_bts_xbow.txt
sprites/bts_rc/wepspr.spr
